### ISSUE TITLE
allOrNone parameter for composite request

### ISSUE THREAD

**Issue by denysvarchenko** [forcedotcom/SalesforceMobileSDK-iOS-Hybrid#154]
Hello!

Currently, we need to use [allOrNone parameter for composite request](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_allornone.htm) for Batch sync up request that is available for Salesforce REST API 49.0.
But it is not possible to specify it for the request because it is hardcoded in the SFBatchSyncUpTarget.m line 158. 
When it will be available for specifying for the SFBatchSyncUpTarget and for SFParentChildrenSyncUpTarget? 

Thank you

**Comment by wmathurin** [comment]
We will take a look in our next release.
In the mean time, you can subclss SFBatchSyncUpTarget and use the custom sync target in your app.
For more information on custom sync targets see https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_native_up_target_def.htm

**Comment by denysvarchenko** [comment]
Do you mean to override the method
`- (void)syncUpRecords:(nonnull SFSmartSyncSyncManager *)syncManager records:(nonnull NSArray<NSMutableDictionary *> *)records fieldlist:(nonnull NSArray *)fieldlist mergeMode:(SFSyncStateMergeMode)mergeMode syncSoupName:(nonnull NSString *)syncSoupName completionBlock:(nonnull SFSyncUpTargetCompleteBlock)completionBlock failBlock:(nonnull SFSyncUpTargetErrorBlock)failBlock`
and replace allOrNone parameter with YES? 
But the subclass may be called from js code?

**Comment by wmathurin** [comment]
Yes, you can invoke custom sync target from javascript.
It would look something like:
```
 {
      "syncName": "MyCustomSyncUp",
      "syncType": "syncUp",
      "soupName": "accounts",
      "target": {
        "iOSImpl": "SFCustomSyncUpTarget",
        "androidImpl": "com.salesforce.androidsdk.mobilesync.target.MyCustomSyncUpTarget",
        "createFieldlist": ["Name"],
        "updateFieldlist": ["Description"]
      },
      "options": {
        "fieldlist": [],
        "mergeMode":"LEAVE_IF_CHANGED"
      }
    }
```

**Comment by wmathurin** [comment]
There is no way to make an entire sync operation atomic. With the allOrNone flag, we could have each batch succeed or fail as one, but you would still end up with a mix of successful and failed batches for the sync itself.
We don't think it would add much semantic wise to treat individual batches atomically.
If it makes sense in your application, please use a custom sync target as described above. We decided not to change the SDK to support that scenario.

**Comment by denysvarchenko** [comment]
Understood you point, Thank you
