### ISSUE TITLE
ParentChild targets for multiple objects relationships

### ISSUE THREAD

**Issue by denysvarchenko** [forcedotcom/SalesforceMobileSDK-iOS-Hybrid#156]
Hello,
According the [doc](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_sync_related.htm?search_text=parentchild) it is possible to upload Parent and Child records using ParentChild sync up/down targets. But there is no info how it is possible to upload several levels of objects using this target, like Account -> Contact -> Address. 

How is it possible using existing and how usersyncs.json should be modified on the Ionic app side?
Or should we use use custom target to upload/download the data using composite request and work with SmartStore manually?

Thank you!

**Comment by wmathurin** [comment]
We don't have out of the box sync targets to deal with more than two levels of objects at once.
The approach other customers have taken is either to build a custom sync target for dealing with such cases, or run multiple syncs and "manually" fixing reference ids between the runs. To make that easier, it is useful to add custom fields to each object and store the locally generated id in those fields and use upsert by external id during sync up.

**Comment by denysvarchenko** [comment]
@wmathurin Thank you for your answer.
To implement this we need to use Composite request API like described [here](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/requests_composite_sobject_tree.htm)?

Could you please also help us with the several points?
1. How these custom targets should be implemented in terms of Hybrid application? Is there any example? I don't remember I've seen any.
2. To upload/download the records using object tree request should we use something like this?
`{
"attributes" : {"type" : "Account", "referenceId" : "ref1"},
"name" : "SampleAccount",
"phone" : "1234567890",
"website" : "www.salesforce.com",
"NumberOfEmployees" : "100",
"industry" : "Banking",
"Contacts" : {
  "records" : [{
     "attributes" : {"type" : "Contact", "referenceId" : "ref2"},
     "lastname" : "Smith",
     "title" : "President",
     "email" : "sample@salesforce.com"
     "Addresses" : {
           "records" : [{
           "attributes" : {"type" : "Address", "referenceId" : "ref4"},
           "city" : "London",
           "street" : "Baker street"
            }]
      },{         
     "attributes" : {"type" : "Contact", "referenceId" : "ref3"},
     "lastname" : "Evans",
     "title" : "Vice President",
     "email" : "sample@salesforce.com"
     }]
  }
}`
3. As we understand from the doc:
       a. if we will have more than five levels or more than five types of different objects(even for two levels) we will need to run multiple syncs and "manually" fixing reference ids between the runs anyway?
       b. if we will have more than 200 of records in total we should divide the objects and run the composite request several times
And summarising if we will have the point a possible in our app it is more profitable to create manual syncs for objects trees instead of using composite request?

Best Regards

**Comment by wmathurin** [comment]
Custom targets can only be implemented natively (see doc https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_native_custom_up_targets.htm). But can be defined/invoked from an hybrid application by using the androidImpl and iOSImpl fields. For an example of a syncs json config with those fields see https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/dev/shared/example.usersyncs.json#L113.

You might be better off synching one object type at a time using a regular sync up. Then fix reference ids before moving to the next object type (down the tree).

**Comment by denysvarchenko** [comment]
@wmathurin We will consider to perform these operations manually. The way you are proposing is much better because it also saves for us all the automatic operations with SmartStore manager after sync down.
Thanks a lot for you help.
