### ISSUE TITLE
HybridViewController does not use isEqualToString

### ISSUE THREAD

**Issue by asikora-sf** [forcedotcom/SalesforceMobileSDK-iOS-Hybrid#162]
https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/blob/357001649ce8ac34ac8cd51f27d96e7e779d73bd/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m#L504

error.domain == should be [error.domain isEqualToString

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/pull/163).
