### ISSUE TITLE
SalesforceMobileSDK-Hybrid Start Page redirect issue

### ISSUE THREAD

**Issue by raveeBunduwongse** [forcedotcom/SalesforceMobileSDK-iOS-Hybrid#208]
As of Spring 23' Release version, we've been experiencing issue on re-direct to home page on both Android and iOS devices.

salesforce-mobilesdk-cordova-plugin: 9.1.1 / 10.2.0

----

We've tried isolating the issue by creating from the sample app and did the following steps:

1. Install any sample app following the instructions: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_samples_build.htm

1. Update "Consumer Key" in bootconfig.json (using the key from XXXX_app connected app)

1. Build the app and run it

1. Login using system admin account in Sandbox

1. Observe redirect behavior

-----

**Observation:**

**iOS:** The page will be blank after login and shows timeout error in the log when accessing "https://XXXXX--XXXX.sandbox.file.force.com/secur/contentDoor?"

**Android:** The page is redirected slowly, takes around ~30 seconds
We're originally building the app using SF Mobile SDK 9.1.1 version, but has also tried replicating the issue using 10.2.0 version. To narrow down the issue, we've tried connecting the app to the Non-preview sandbox and was not able to replicate this issue on the non-preview sandbox.

**Comment by gkotula** [comment]
Hi @raveeBunduwongse just to be sure I can accurately diagnose the issue, do I understand the following correctly?

1. The sample app on iOS and Android are both timing out on login to the preview sandbox Orgs.
2. Non preview sandbox Orgs are not showing the issue.
3. This is happening even with the latest MSDK release `10.2.0`.

**Comment by raveeBunduwongse** [comment]
Hi @gkotula, that is correct, thanks for the reply!

1. The sample app on iOS and Android are both timing out on login to the preview sandbox Orgs.
> Both iOS and Android both exhibit observed slow loading of the contentDoor JS file (>20 seconds). But only iOS experience timeout issue.

2. Non preview sandbox Orgs are not showing the issue.
> Correct, only after Spring '23 is applied do our Connected app experience the issue, now that the Spring '23 salesforce update has been deployed, Prod Orgs is now also getting same issue.

3. This is happening even with the latest MSDK release 10.2.0.
> Correct.

Now that the Spring '23 has been deployed to non-preview sandboxes, we can now observe slow loading of the `contentDoor` JS file from file.force. Due to that, we have implemented workaround to prevent the timeout issue, but the content loading itself is still happening.

**Comment by gkotula** [comment]
@raveeBunduwongse Thank you for the clarification 👍   You are not the first person to observe slow loading times coming from that endpoint recently.  I am ensuring the proper people are notified about the possible performance degradation, but all of this is suggesting that this is likely _not_ a Salesforce Mobile SDK issue.  We are internally discussing whether the SDK timeout values should be tweaked, but the core problem seems to be that slow load.

We're looking into it!

**Comment by raveeBunduwongse** [comment]
@gkotula  Thank you for the reply, please do let us know if any additional information / clarification is needed!

**Comment by raveeBunduwongse** [comment]
One question @gkotula , is there any planned fix date for this issue so we can discuss with the business on the possible options. Currently this is affecting the production operation. Thanks!

**Comment by gkotula** [comment]
Actually, @raveeBunduwongse what Cloud products is your Org subscribed to?  Service, Marketing, etc.?  Knowing how your Org is configured may expedite the solution.

**Comment by raveeBunduwongse** [comment]
Appreciate the suggestion, the workaround with the increase in timeout config has been implemented to prevent timeout.

Our subscription is Sales Cloud. Use case is to develop a custom tablet application using Salesforce Mobile SDK Hybrid  for sales people to manage their sales activities - supports both iOS and Android

**Comment by wmathurin** [comment]
Closing since there is a workaround.
